// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBunTbMY6mtwU8WhuOXTs-JntMQfN4V-GI',
    appId: '1:482718726512:web:e483e8df6bd4fdffde77b5',
    messagingSenderId: '482718726512',
    projectId: 'aula2410flutter',
    authDomain: 'aula2410flutter.firebaseapp.com',
    storageBucket: 'aula2410flutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAX9f8sX6vPULU7_C1PlNbrNhP4gQcYQNg',
    appId: '1:482718726512:android:6a70020b03a467d8de77b5',
    messagingSenderId: '482718726512',
    projectId: 'aula2410flutter',
    storageBucket: 'aula2410flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0fVGMn0RaLOhEHvMw6K6s79vLmuJB9h8',
    appId: '1:482718726512:ios:234228e59571a4a6de77b5',
    messagingSenderId: '482718726512',
    projectId: 'aula2410flutter',
    storageBucket: 'aula2410flutter.appspot.com',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0fVGMn0RaLOhEHvMw6K6s79vLmuJB9h8',
    appId: '1:482718726512:ios:234228e59571a4a6de77b5',
    messagingSenderId: '482718726512',
    projectId: 'aula2410flutter',
    storageBucket: 'aula2410flutter.appspot.com',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBunTbMY6mtwU8WhuOXTs-JntMQfN4V-GI',
    appId: '1:482718726512:web:668b0c180e5b4f76de77b5',
    messagingSenderId: '482718726512',
    projectId: 'aula2410flutter',
    authDomain: 'aula2410flutter.firebaseapp.com',
    storageBucket: 'aula2410flutter.appspot.com',
  );

}